### ISSUE TITLE
`gulp-css-url-rebase` wird schon lange nicht mehr maintained

### ISSUE THREAD

**Issue by mpdude** [webfactory/webfactory-gulp-preset#9]
[`gulp-css-url-rebase`](https://www.npmjs.com/package/gulp-css-url-rebase) scheint vor längerer Zeit aufgegeben worden zu sein. Es benutzt `validator` in der Version 3.x, wo inzwischen eine Version 13.x existiert.

Damit laufen wir in Projekten ([Beispiel](https://github.com/webfactory/youthpass/security/dependabot/yarn.lock/validator/open)) in Dependabot-Warnungen, die wir nicht einfach beseitigen können.

Ich weiß, dass URL-Rebasing ein vertracktes Thema ist und dass wir froh sind, eine Lösung zu haben, die "funktioniert". 

Vielleicht können wir aber doch mittelfristig schauen, welches Paket eine aktuell gepflegte Lösung bietet?

**Comment by polarbirke** [comment]
Dieses Issue ist veraltet, URL rebasing läuft schon ewig via postcss-url.
